# Generated by Django 4.1b1 on 2022-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="designation",
            field=models.CharField(
                choices=[("330", "330"), ("132", "132")], max_length=4, null=True
            ),
        ),
    ]
