# Generated by Django 4.1b1 on 2022-07-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0003_rename_station_300_station_132_station_330"),
        ("stations_330", "0002_alter_station_330_options_alter_station_330_slug"),
        ("users", "0002_user_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="station_132",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations_132.station_132",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="station_330",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stations_330.station_330",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                choices=[("330", "330kV"), ("132", "132kV")], max_length=4, null=True
            ),
        ),
    ]
