# Generated by Django 4.1b1 on 2022-07-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0002_alter_station_330_options_alter_station_330_slug"),
        ("stations_132", "0003_rename_station_300_station_132_station_330"),
        ("users", "0004_alter_user_station_132_alter_user_station_330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="station_132",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="stations_132.station_132",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="station_330",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="stations_330.station_330",
            ),
        ),
    ]
