# Generated by Django 4.1rc1 on 2022-08-16 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations_132", "0005_station_132_address_station_132_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ayede132ReadingSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ayede132HourlyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("hour", models.IntegerField()),
                ("frequency", models.FloatField()),
                ("iwo_iseyin_kv", models.FloatField()),
                ("iwo_iseyin_a", models.FloatField()),
                ("iwo_iseyin_mw", models.FloatField()),
                ("iwo_iseyin_mvar", models.FloatField()),
                ("jericho_kv", models.FloatField()),
                ("jericho_a", models.FloatField()),
                ("jericho_mw", models.FloatField()),
                ("jericho_mvar", models.FloatField()),
                ("mcpherson_kv", models.FloatField()),
                ("mcpherson_a", models.FloatField()),
                ("mcpherson_mw", models.FloatField()),
                ("mcpherson_mvar", models.FloatField()),
                ("t1_kv", models.FloatField()),
                ("t1_a", models.FloatField(blank=True, null=True)),
                ("t1_mw", models.FloatField(blank=True, null=True)),
                ("t1_mvar", models.FloatField(blank=True, null=True)),
                ("t2_kv", models.FloatField()),
                ("t2_a", models.FloatField(blank=True, null=True)),
                ("t2_mw", models.FloatField(blank=True, null=True)),
                ("t2_mvar", models.FloatField(blank=True, null=True)),
                ("t3_kv", models.FloatField()),
                ("t3_a", models.FloatField(blank=True, null=True)),
                ("t3_mw", models.FloatField(blank=True, null=True)),
                ("t3_mvar", models.FloatField(blank=True, null=True)),
                ("total_mw", models.FloatField(blank=True, null=True)),
                ("total_mvar", models.FloatField(blank=True, null=True)),
                ("oluyole", models.FloatField()),
                ("express", models.FloatField()),
                ("liberty", models.FloatField()),
                ("industrial", models.FloatField()),
                ("interchange", models.FloatField()),
                ("iyaganku", models.FloatField()),
                ("apata", models.FloatField()),
                ("eleyele", models.FloatField()),
                ("lanlate", models.FloatField()),
                ("spare", models.FloatField(blank=True, null=True)),
                ("uploaded", models.BooleanField(default=False)),
                ("user_name", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "reading_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_readings",
                        to="ayede132hourlyreadings.ayede132readingsheet",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_readings",
                        to="stations_132.station_132",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
