# Generated by Django 4.1rc1 on 2022-08-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ayede132hourlyreadings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ayede132hourlyreading",
            old_name="total_mvar",
            new_name="total_load_mvar",
        ),
        migrations.RenameField(
            model_name="ayede132hourlyreading",
            old_name="total_mw",
            new_name="total_load_mw",
        ),
    ]
