# Generated by Django 4.1 on 2022-08-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0006_station_132_acc_station_load"),
        (
            "ayede132hourlyreadings",
            "0002_rename_total_mvar_ayede132hourlyreading_total_load_mvar_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Ayede132GoogleSheets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("google_sheet_title", models.CharField(max_length=60)),
                ("google_sheet_id", models.CharField(max_length=200)),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="station_google_sheets",
                        to="stations_132.station_132",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ayede 132 Google Sheet",
            },
        ),
    ]
