# Generated by Django 4.1 on 2022-08-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ayede132hourlyreadings", "0003_ayede132googlesheets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ayede132hourlyreading",
            old_name="uploaded",
            new_name="is_uploaded",
        ),
    ]
