# Generated by Django 4.0.7 on 2022-09-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations_132', '0006_station_132_acc_station_load'),
        ('ayede132hourlyreadings', '0004_rename_uploaded_ayede132hourlyreading_is_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayede132googlesheets',
            options={'verbose_name': 'Ayede 132 Google Sheet', 'verbose_name_plural': 'Ayede 132 Google Sheets'},
        ),
        migrations.CreateModel(
            name='Ayede132GoogleSheetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('sheet_range', models.CharField(blank=True, max_length=10, null=True)),
                ('station', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stations_132.station_132')),
            ],
            options={
                'verbose_name': 'Ayede 132 Google Sheet Range',
                'verbose_name_plural': 'Ayede 132 Google Sheet Range',
            },
        ),
    ]
