# Generated by Django 4.1b1 on 2022-07-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations_330", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station_132",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("abbrevation", models.CharField(max_length=5)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="stations_132/images")),
                (
                    "station_300",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations_132",
                        to="stations_330.station_330",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
