# Generated by Django 4.1b1 on 2022-07-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station_132",
            options={
                "verbose_name": "132kV Station",
                "verbose_name_plural": "132kV Stations",
            },
        ),
    ]
