# Generated by Django 4.1b1 on 2022-07-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0002_alter_station_132_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station_132",
            old_name="station_300",
            new_name="station_330",
        ),
    ]
