# Generated by Django 4.1b1 on 2022-07-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0003_rename_station_300_station_132_station_330"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_132",
            name="station_type",
            field=models.CharField(default="132", max_length=3),
        ),
    ]
