# Generated by Django 4.1rc1 on 2022-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0004_station_132_station_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_132",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="station_132",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="station_132",
            name="state",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="station_132",
            name="town",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
