# Generated by Django 4.1rc1 on 2022-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0005_station_132_address_station_132_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_132",
            name="acc_station_load",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
