# Generated by Django 4.1.1 on 2022-09-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0006_station_132_acc_station_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_132",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
