# Generated by Django 4.1rc1 on 2022-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operational_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalreport",
            name="frequency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationalreport",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("y", "Yellow Phase"),
                    ("b", "Blue Phase"),
                    ("r", "Red Phase"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="operationalreport",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[("l/s", "Load Shedding"), ("e/f", "Earth Fault")],
                max_length=4,
                null=True,
            ),
        ),
    ]
