# Generated by Django 4.1rc1 on 2022-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operational_reports",
            "0002_operationalreport_frequency_operationalreport_phase_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalreport",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("y", "Yellow Phase"),
                    ("y&b", "Yellow and Blue Phase"),
                    ("b", "Blue Phase"),
                    ("b&r", "Blue and Red Phase"),
                    ("r", "Red Phase"),
                    ("r&y", "Red and Yellow Phase"),
                    ("r,y&b", "All Phases"),
                ],
                max_length=7,
                null=True,
            ),
        ),
    ]
