# Generated by Django 4.1rc1 on 2022-08-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0005_station_132_address_station_132_country_and_more"),
        ("stations_330", "0004_station_330_address_station_330_country_and_more"),
        ("operational_reports", "0003_alter_operationalreport_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalreport",
            name="station_132",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_report",
                to="stations_132.station_132",
            ),
        ),
        migrations.AddField(
            model_name="operationalreport",
            name="station_132_330",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_report",
                to="stations_330.station_330",
            ),
        ),
        migrations.AlterField(
            model_name="operationalreport",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("y", "Yellow Phase"),
                    ("b", "Blue Phase"),
                    ("r", "Red Phase"),
                    ("y&b", "Yellow and Blue Phase"),
                    ("b&r", "Blue and Red Phase"),
                    ("r&y", "Red and Yellow Phase"),
                    ("r,y&b", "All Phases"),
                ],
                max_length=7,
                null=True,
            ),
        ),
    ]
