# Generated by Django 4.1rc1 on 2022-08-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0005_station_132_address_station_132_country_and_more"),
        ("stations_330", "0004_station_330_address_station_330_country_and_more"),
        ("operational_reports", "0004_operationalreport_station_132_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalreport",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationalreport",
            name="dispatch",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="operationalreport",
            name="load_loss",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="operationalreport",
            name="station_132",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_reports",
                to="stations_132.station_132",
            ),
        ),
        migrations.AlterField(
            model_name="operationalreport",
            name="station_132_330",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_reports",
                to="stations_330.station_330",
            ),
        ),
    ]
