# Generated by Django 4.1rc1 on 2022-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operational_reports", "0005_operationalreport_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalreport",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("l/s", "Load Shedding"),
                    ("e/f", "Earth Fault"),
                    ("o/c", "Over Current"),
                    ("e/f&o/c", "Earth Fault / Over Current"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
