# Generated by Django 4.1.1 on 2022-09-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operational_reports", "0006_alter_operationalreport_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalreport",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
