# Generated by Django 4.1rc1 on 2022-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ayede330HourlyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("hour", models.IntegerField()),
                ("frequency", models.FloatField()),
                ("oshogbo_kv", models.FloatField()),
                ("oshogbo_a", models.FloatField()),
                ("oshogbo_mw", models.FloatField()),
                ("oshogbo_mvar", models.FloatField()),
                ("olorunsogo_kv", models.FloatField()),
                ("olorunsogo_a", models.FloatField()),
                ("olorunsogo_mw", models.FloatField(blank=True, null=True)),
                ("olorunsogo_mvar", models.FloatField(blank=True, null=True)),
                ("t1a_kv", models.FloatField(blank=True, null=True)),
                ("t1a_a", models.FloatField(blank=True, null=True)),
                ("t1a_mw", models.FloatField(blank=True, null=True)),
                ("t1a_mvar", models.FloatField(blank=True, null=True)),
                ("t2a_kv", models.FloatField()),
                ("t2a_a", models.FloatField()),
                ("t2a_mw", models.FloatField(blank=True, null=True)),
                ("t2a_mvar", models.FloatField(blank=True, null=True)),
                ("t2b_kv", models.FloatField()),
                ("t2b_a", models.FloatField()),
                ("t2b_mw", models.FloatField()),
                ("t2b_mvar", models.FloatField()),
                ("sagamu_kv", models.FloatField()),
                ("sagamu_a", models.FloatField()),
                ("sagamu_mw", models.FloatField()),
                ("sagamu_mvar", models.FloatField()),
                ("jericho_kv", models.FloatField()),
                ("jericho_a", models.FloatField()),
                ("jericho_mw", models.FloatField()),
                ("jericho_mvar", models.FloatField()),
                ("iwo_iseyin_kv", models.FloatField()),
                ("iwo_iseyin_a", models.FloatField()),
                ("iwo_iseyin_mw", models.FloatField()),
                ("iwo_iseyin_mvar", models.FloatField()),
                ("total_load_a", models.IntegerField(blank=True, null=True)),
                ("total_load_mw", models.IntegerField(blank=True, null=True)),
                ("uploaded", models.BooleanField(default=False)),
                ("daily_area_load", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
