# Generated by Django 4.1rc1 on 2022-07-31 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ayede330hourlyreadings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayede330hourlyreading",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ayede330hourlyreading",
            name="user_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
