# Generated by Django 4.1rc1 on 2022-08-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayede330hourlyreadings", "0002_ayede330hourlyreading_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayede330hourlyreading",
            name="frequency",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
