# Generated by Django 4.1rc1 on 2022-08-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0004_station_330_address_station_330_country_and_more"),
        ("ayede330hourlyreadings", "0004_ayede330hourlyreading_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayede330hourlyreading",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hourly_reading",
                to="stations_330.station_330",
            ),
        ),
    ]
