# Generated by Django 4.1rc1 on 2022-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayede330hourlyreadings", "0005_alter_ayede330hourlyreading_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
