# Generated by Django 4.1rc1 on 2022-08-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayede330hourlyreadings", "0006_readingsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingsheet",
            name="hourly_reading",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ayede330hourlyreadings.ayede330hourlyreading",
            ),
        ),
    ]
