# Generated by Django 4.1rc1 on 2022-08-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayede330hourlyreadings", "0008_ayede330readingsheet_delete_readingsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayede330hourlyreading",
            name="reading_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hourly_readings",
                to="ayede330hourlyreadings.ayede330readingsheet",
            ),
        ),
    ]
