# Generated by Django 4.1rc1 on 2022-08-15 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayede330hourlyreadings", "0009_ayede330hourlyreading_reading_sheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ayede330readingsheet",
            name="name",
        ),
        migrations.AddField(
            model_name="ayede330readingsheet",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 15, 20, 3, 47, 740475, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
