# Generated by Django 4.1rc1 on 2022-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayede330hourlyreadings", "0012_ayede330googlesheets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ayede330googlesheets",
            options={
                "verbose_name": "Ayede 330 Google Sheet",
                "verbose_name_plural": "Ayede 330 Google Sheets",
            },
        ),
        migrations.AlterField(
            model_name="ayede330googlesheets",
            name="google_sheet_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="ayede330googlesheets",
            name="google_sheet_title",
            field=models.CharField(max_length=60),
        ),
    ]
