# Generated by Django 4.0.7 on 2022-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayede330hourlyreadings', '0015_rename_uploaded_ayede330hourlyreading_is_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='acc_station_load_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='active_load_flow_range_olorunsogo_mw',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='active_load_flow_range_osogbo_mw',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='daily_area_load_range',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='transformer_hourly_load_range_t1a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='transformer_hourly_load_range_t2a',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ayede330hourlyreading',
            name='transformer_hourly_load_range_t2b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
