# Generated by Django 4.0.7 on 2022-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayede330hourlyreadings', '0016_ayede330hourlyreading_acc_station_load_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayede330GoogleSheetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('sheet_range', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='acc_station_load_range',
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='active_load_flow_range_olorunsogo_mw',
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='active_load_flow_range_osogbo_mw',
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='daily_area_load_range',
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='transformer_hourly_load_range_t1a',
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='transformer_hourly_load_range_t2a',
        ),
        migrations.RemoveField(
            model_name='ayede330hourlyreading',
            name='transformer_hourly_load_range_t2b',
        ),
    ]
