# Generated by Django 4.0.7 on 2022-09-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayede330hourlyreadings', '0017_ayede330googlesheetrange_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayede330googlesheetrange',
            options={'verbose_name': 'Ayede 330 Google Sheet Range', 'verbose_name_plural': 'Ayede 330 Google Sheet Range'},
        ),
        migrations.AlterModelOptions(
            name='ayede330hourlyreading',
            options={'verbose_name': 'Ayede 330 Hourly Reading', 'verbose_name_plural': 'Ayede 330 Hourly Readings'},
        ),
        migrations.AlterModelOptions(
            name='ayede330readingsheet',
            options={'verbose_name': 'Ayede 330 Reading Sheet', 'verbose_name_plural': 'Ayede 330 Reading Sheets'},
        ),
    ]
