# Generated by Django 4.0.7 on 2022-09-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ayede330hourlyreadings', '0018_alter_ayede330googlesheetrange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayede330hourlyreading',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hourly_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
