# Generated by Django 4.0.7 on 2022-09-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations_330', '0008_remove_station_330_acc_station_load_range_and_more'),
        ('ayede330hourlyreadings', '0019_alter_ayede330hourlyreading_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayede330googlesheetrange',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations_330.station_330'),
        ),
    ]
