# Generated by Django 4.1rc1 on 2022-07-25 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations_132", "0004_station_132_station_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectionGuarantee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "for_a",
                    models.CharField(
                        choices=[("s.g", "S.G"), ("w&t.p", "W&T.P"), ("w.t", "W.T")],
                        max_length=6,
                    ),
                ),
                ("to_be_issued", models.DateField()),
                ("to_be_issued_to", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=25)),
                ("to_be_issued_at", models.DateTimeField()),
                ("to_be_surrendered_at", models.DateTimeField()),
                ("description_of_apparatus", models.TextField()),
                ("additional_apparatus", models.TextField(blank=True, null=True)),
                ("advance_request_name", models.CharField(max_length=30)),
                ("signature_of_applicant", models.CharField(max_length=50)),
                ("received_at", models.DateTimeField()),
                ("outage", models.IntegerField()),
                ("working_time", models.DurationField(blank=True, null=True)),
                ("switching_time", models.DateTimeField(blank=True, null=True)),
                (
                    "apparatus_outage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("apparatus_outage_to", models.DateTimeField(blank=True, null=True)),
                ("approved_by_name", models.CharField(max_length=50)),
                ("approved_to", models.DateTimeField(blank=True, null=True)),
                (
                    "final_approval_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("final_approval_at", models.DateTimeField(blank=True, null=True)),
                (
                    "advance_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protection_guarantees_advance_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "applied_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection_guarantees",
                        to="stations_132.station_132",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protection_guarantees_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "final_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protection_guarantees_final_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protection_guarantees_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
