# Generated by Django 4.1rc1 on 2022-07-25 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("protection_guarantees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionguarantee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protection_guarantees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="protectionguarantee",
            name="user_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="protectionguarantee",
            name="advance_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="protection_guarantees_advance_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="protectionguarantee",
            name="advance_request_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="protectionguarantee",
            name="signature_of_applicant",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
