# Generated by Django 4.1rc1 on 2022-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protection_guarantees", "0002_protectionguarantee_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectionguarantee",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
