# Generated by Django 4.1rc1 on 2022-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protection_guarantees", "0003_alter_protectionguarantee_received_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectionguarantee",
            name="approved_by_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
