# Generated by Django 4.1rc1 on 2022-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protection_guarantees", "0004_alter_protectionguarantee_approved_by_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionguarantee",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
