# Generated by Django 4.1rc1 on 2022-07-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protection_guarantees", "0005_protectionguarantee_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionguarantee",
            name="received_by_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
