# Generated by Django 4.1rc1 on 2022-07-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0004_station_132_station_type"),
        ("stations_330", "0003_station_330_station_type"),
        ("protection_guarantees", "0006_protectionguarantee_received_by_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protectionguarantee",
            name="applied_to",
        ),
        migrations.AddField(
            model_name="protectionguarantee",
            name="applied_to_132",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protection_guarantees_132",
                to="stations_132.station_132",
            ),
        ),
        migrations.AddField(
            model_name="protectionguarantee",
            name="applied_to_330",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protection_guarantees_330",
                to="stations_330.station_330",
            ),
        ),
    ]
