# Generated by Django 4.1rc1 on 2022-07-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0003_station_330_station_type"),
        (
            "protection_guarantees",
            "0008_alter_protectionguarantee_applied_to_132_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionguarantee",
            name="applied_to_132_330",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protection_guarantees_132_330",
                to="stations_330.station_330",
            ),
        ),
    ]
