# Generated by Django 4.1rc1 on 2022-07-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0003_station_330_station_type"),
        ("stations_132", "0004_station_132_station_type"),
        ("protection_guarantees", "0009_protectionguarantee_applied_to_132_330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectionguarantee",
            name="applied_to_132",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protection_guarantees",
                to="stations_132.station_132",
            ),
        ),
        migrations.AlterField(
            model_name="protectionguarantee",
            name="applied_to_330",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protection_guarantees",
                to="stations_330.station_330",
            ),
        ),
    ]
