# Generated by Django 4.1rc1 on 2022-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "protection_guarantees",
            "0010_alter_protectionguarantee_applied_to_132_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionguarantee",
            name="is_acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
