# Generated by Django 4.1b1 on 2022-07-15 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations_132", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "station_132",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeders",
                        to="stations_132.station_132",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
