# Generated by Django 4.1b1 on 2022-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeders", "0002_feeder_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeder",
            name="slug",
            field=models.SlugField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
