# Generated by Django 4.1b1 on 2022-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeders", "0003_alter_feeder_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeder",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
