# Generated by Django 4.1b1 on 2022-07-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station_330",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("abbrevation", models.CharField(max_length=5)),
                ("slug", models.SlugField()),
                ("image", models.ImageField(upload_to="stations_330/images")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
