# Generated by Django 4.1b1 on 2022-07-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station_330",
            options={
                "verbose_name": "330kV Station",
                "verbose_name_plural": "330kV Stations",
            },
        ),
        migrations.AlterField(
            model_name="station_330",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
