# Generated by Django 4.1b1 on 2022-07-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0002_alter_station_330_options_alter_station_330_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_330",
            name="station_type",
            field=models.CharField(default="330", max_length=3),
        ),
    ]
