# Generated by Django 4.1rc1 on 2022-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0004_station_330_address_station_330_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_330",
            name="acc_station_load",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
