# Generated by Django 4.1rc1 on 2022-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0005_station_330_acc_station_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_330",
            name="active_load_flow",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="station_330",
            name="daily_area_load",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="station_330",
            name="transformer_hourly_load",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
