# Generated by Django 4.1rc1 on 2022-08-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0006_station_330_active_load_flow_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station_330",
            old_name="acc_station_load",
            new_name="acc_station_load_range",
        ),
        migrations.RenameField(
            model_name="station_330",
            old_name="active_load_flow",
            new_name="active_load_flow_range",
        ),
        migrations.RenameField(
            model_name="station_330",
            old_name="daily_area_load",
            new_name="daily_area_load_range",
        ),
        migrations.RenameField(
            model_name="station_330",
            old_name="transformer_hourly_load",
            new_name="transformer_hourly_load_range",
        ),
    ]
