# Generated by Django 4.0.7 on 2022-09-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations_330', '0007_rename_acc_station_load_station_330_acc_station_load_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_330',
            name='acc_station_load_range',
        ),
        migrations.RemoveField(
            model_name='station_330',
            name='active_load_flow_range',
        ),
        migrations.RemoveField(
            model_name='station_330',
            name='daily_area_load_range',
        ),
        migrations.RemoveField(
            model_name='station_330',
            name='transformer_hourly_load_range',
        ),
    ]
