# Generated by Django 4.1.1 on 2022-09-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0008_remove_station_330_acc_station_load_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station_330",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
