# Generated by Django 4.0.7 on 2022-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('broadcast_on', models.DateTimeField()),
                ('is_displayed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
