# Generated by Django 4.0.7 on 2022-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0002_scheduledreport_protection_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='broadcast_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
