# Generated by Django 4.1b1 on 2022-07-20 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations_330", "0002_alter_station_330_options_alter_station_330_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations_132", "0003_rename_station_300_station_132_station_330"),
    ]

    operations = [
        migrations.CreateModel(
            name="TroubleReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField()),
                ("user_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "acknowledged_by_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "to_authority",
                    models.CharField(
                        choices=[("pmso", "PM(SO)"), ("pmt", "PM(T)")], max_length=20
                    ),
                ),
                (
                    "location_of_trouble",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[("iso", "ISO"), ("tsp", "TSP")], max_length=30
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=50, null=True)),
                ("apparatus_in_trouble", models.TextField()),
                ("description_of_trouble", models.TextField(blank=True, null=True)),
                ("description_of_switching", models.TextField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station_or_line_station_132",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trouble_reports",
                        to="stations_132.station_132",
                    ),
                ),
                (
                    "station_or_line_station_330",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trouble_reports",
                        to="stations_330.station_330",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trouble_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
