# Generated by Django 4.1b1 on 2022-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("troublereports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="troublereport",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
