# Generated by Django 4.1rc1 on 2022-07-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("troublereports", "0003_alter_troublereport_to_authority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="troublereport",
            options={"ordering": ["-created"]},
        ),
    ]
