# Generated by Django 4.1rc1 on 2022-07-22 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations_330", "0003_station_330_station_type"),
        ("troublereports", "0004_alter_troublereport_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_has_seen", models.BooleanField(default=False)),
                (
                    "from_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_from",
                        to="stations_330.station_330",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_to",
                        to="stations_330.station_330",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trouble_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="troublereports.troublereport",
                    ),
                ),
            ],
        ),
    ]
