# Generated by Django 4.1rc1 on 2022-07-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="trouble_report",
        ),
        migrations.AddField(
            model_name="notification",
            name="text",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
