# Generated by Django 4.1rc1 on 2022-07-22 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_notification_trouble_report_notification_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
