# Generated by Django 4.1rc1 on 2022-07-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0004_station_132_station_type"),
        ("stations_330", "0003_station_330_station_type"),
        ("notifications", "0004_remove_notification_from_station_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="to_station_132",
            field=models.ManyToManyField(
                related_name="notifications_to", to="stations_132.station_132"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="to_station_330",
            field=models.ManyToManyField(
                related_name="notifications_to", to="stations_330.station_330"
            ),
        ),
    ]
