# Generated by Django 4.1rc1 on 2022-07-23 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations_132", "0004_station_132_station_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stations_330", "0003_station_330_station_type"),
        ("notifications", "0006_remove_notification_created_at_notification_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="from_station_132",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_from",
                to="stations_132.station_132",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="from_station_330",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_from",
                to="stations_330.station_330",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="from_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_from",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
