# Generated by Django 4.1rc1 on 2022-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations_330", "0003_station_330_station_type"),
        ("stations_132", "0004_station_132_station_type"),
        ("notifications", "0007_alter_notification_from_station_132_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="to_station_132",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications_to",
                to="stations_132.station_132",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="to_station_330",
            field=models.ManyToManyField(
                blank=True,
                related_name="notifications_to",
                to="stations_330.station_330",
            ),
        ),
    ]
