# Generated by Django 4.1rc1 on 2022-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_alter_notification_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("display_time", models.DateTimeField()),
                ("is_disabled", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
