# Generated by Django 4.1.1 on 2022-09-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0011_schedulednotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScheduledNotification",
        ),
    ]
